#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _ExpSynSTDP_reg(void);
extern void _IClampISI_reg(void);
extern void _IClampISIBurst_reg(void);
extern void _IClampNoise_reg(void);
extern void _IPSPanaly_reg(void);
extern void _ISICalc_reg(void);
extern void _KM_2_reg(void);
extern void _KahpM95_reg(void);
extern void _LcaMig_reg(void);
extern void _MyAMPA_reg(void);
extern void _MyNMDA_reg(void);
extern void _NewNoise_reg(void);
extern void _STDPE2Syn_reg(void);
extern void _analysisAP_reg(void);
extern void _bgka_reg(void);
extern void _borgkm_reg(void);
extern void _cad_reg(void);
extern void _cagk_morse_reg(void);
extern void _cal_poirazi_reg(void);
extern void _ccanl_reg(void);
extern void _dist_ca_peak_reg(void);
extern void _distr_reg(void);
extern void _epspcount_reg(void);
extern void _hd_reg(void);
extern void _ichan2_reg(void);
extern void _izap_reg(void);
extern void _kadistmig_reg(void);
extern void _kaproxmig_reg(void);
extern void _kdr_mig_reg(void);
extern void _km_reg(void);
extern void _mkm_reg(void);
extern void _my_exp2syn_reg(void);
extern void _my_km_reg(void);
extern void _na3n_reg(void);
extern void _plasticityModule_n_reg(void);
extern void _regn_stim_reg(void);
extern void _sinosc_reg(void);
extern void _vmax2_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," ExpSynSTDP.mod");
    fprintf(stderr," IClampISI.mod");
    fprintf(stderr," IClampISIBurst.mod");
    fprintf(stderr," IClampNoise.mod");
    fprintf(stderr," IPSPanaly.mod");
    fprintf(stderr," ISICalc.mod");
    fprintf(stderr," KM_2.mod");
    fprintf(stderr," KahpM95.mod");
    fprintf(stderr," LcaMig.mod");
    fprintf(stderr," MyAMPA.mod");
    fprintf(stderr," MyNMDA.mod");
    fprintf(stderr," NewNoise.mod");
    fprintf(stderr," STDPE2Syn.mod");
    fprintf(stderr," analysisAP.mod");
    fprintf(stderr," bgka.mod");
    fprintf(stderr," borgkm.mod");
    fprintf(stderr," cad.mod");
    fprintf(stderr," cagk_morse.mod");
    fprintf(stderr," cal_poirazi.mod");
    fprintf(stderr," ccanl.mod");
    fprintf(stderr," dist_ca_peak.mod");
    fprintf(stderr," distr.mod");
    fprintf(stderr," epspcount.mod");
    fprintf(stderr," hd.mod");
    fprintf(stderr," ichan2.mod");
    fprintf(stderr," izap.mod");
    fprintf(stderr," kadistmig.mod");
    fprintf(stderr," kaproxmig.mod");
    fprintf(stderr," kdr_mig.mod");
    fprintf(stderr," km.mod");
    fprintf(stderr," mkm.mod");
    fprintf(stderr," my_exp2syn.mod");
    fprintf(stderr," my_km.mod");
    fprintf(stderr," na3n.mod");
    fprintf(stderr," plasticityModule_n.mod");
    fprintf(stderr," regn_stim.mod");
    fprintf(stderr," sinosc.mod");
    fprintf(stderr," vmax2.mod");
    fprintf(stderr, "\n");
  }
  _ExpSynSTDP_reg();
  _IClampISI_reg();
  _IClampISIBurst_reg();
  _IClampNoise_reg();
  _IPSPanaly_reg();
  _ISICalc_reg();
  _KM_2_reg();
  _KahpM95_reg();
  _LcaMig_reg();
  _MyAMPA_reg();
  _MyNMDA_reg();
  _NewNoise_reg();
  _STDPE2Syn_reg();
  _analysisAP_reg();
  _bgka_reg();
  _borgkm_reg();
  _cad_reg();
  _cagk_morse_reg();
  _cal_poirazi_reg();
  _ccanl_reg();
  _dist_ca_peak_reg();
  _distr_reg();
  _epspcount_reg();
  _hd_reg();
  _ichan2_reg();
  _izap_reg();
  _kadistmig_reg();
  _kaproxmig_reg();
  _kdr_mig_reg();
  _km_reg();
  _mkm_reg();
  _my_exp2syn_reg();
  _my_km_reg();
  _na3n_reg();
  _plasticityModule_n_reg();
  _regn_stim_reg();
  _sinosc_reg();
  _vmax2_reg();
}
